language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - hsp4567@naver.com


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springmvcboard-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    wait-until-deployed: true
    on:
      repo: hsp0404/SpringMVCBoard
      branch: master