language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - hsp4567@naver.com


before_deploy:
  - zip -r SpringMVCBoard *
  - mkdir -p deploy
  - mv SpringMVCBoard.zip deploy/SpringMVCBoard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springmvcboard-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: hsp0404/SpringMVCBoard
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springmvcboard-deploy
    key: SpringMVCBoard.zip
    bundle_type: zip
    application: SpringMVCBoard
    deployment_group: SpringMVCBoard-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: hsp0404/SpringMVCBoard
      branch: master